version: '3'
services:
  database:
    build: .
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: socialnetwork
      TZ: Europe/Moscow